numero = int(input("Informe um número para ver sua tabuada: "))

print("=========")
print("{} x {} = {}".format(numero, 1, numero, numero*1))
print("{} x {} = {}".format(numero, 2, numero, numero*2))
print("{} x {} = {}".format(numero, 3, numero, numero*3))
print("{} x {} = {}".format(numero, 4, numero, numero*4))
print("{} x {} = {}".format(numero, 5, numero, numero*5))
print("{} x {} = {}".format(numero, 6, numero, numero*6))
print("{} x {} = {}".format(numero, 7, numero, numero*7))
print("{} x {} = {}".format(numero, 8, numero, numero*8))
print("{} x {} = {}".format(numero, 9, numero, numero*9))
print("{} x {} = {}".format(numero, 10, numero, numero*10))
print("=========")